/********************************************************************
 *   This C program was generated by spl2c, the Shakespeare to C    *
 *          converter by Jon Åslund and Karl Hasselström.           *
 ********************************************************************/

/* libspl definitions and function prototypes */
#include <spl.h>

int main(void)
{
  /******************************************************************
   * PRIME NUMBER COMPUTATION IN COPENHAGEN                         *
   ******************************************************************/
  
  CHARACTER *romeo;                       /* a young man of Verona */
  CHARACTER *juliet;                      /* a young woman */
  CHARACTER *hamlet;                      /* a temporary variable from Denmark */
  CHARACTER *the_ghost;                   /* a limiting factor ( and by a remarkable coincidence also Hamlet ' s father ) */
  
  int comp1, comp2;
  
  global_initialize();
  
  romeo = initialize_character("Romeo");
  juliet = initialize_character("Juliet");
  hamlet = initialize_character("Hamlet");
  the_ghost = initialize_character("The Ghost");
  
  act_i:                                  /* Interview with the other side */
  
  act_i_scene_i:                          /* At the last hour before dawn */
  
  enter_scene(14, the_ghost);
  enter_scene(14, juliet);
  
  activate_character(20, the_ghost);
  assign(17, second_person, 2*2*2*1);
  assign(18, second_person, int_sub(18, int_square(18, value_of(18, second_person)), 2*1));
  char_output(18, second_person);
  
  activate_character(23, juliet);
  int_input(21, second_person);
  
  exit_scene(23, the_ghost);
  
  enter_scene(25, romeo);
  
  activate_character(31, juliet);
  assign(28, second_person, 2*1);
  
  act_ii:                                 /* Determining divisibility */
  
  act_ii_scene_i:                         /* A private conversation */
  
  activate_character(38, juliet);
  comp1 = value_of(36, second_person);
  comp2 = the_ghost->value;
  truth_flag = (comp1 > comp2);
  
  activate_character(41, romeo);
  if (truth_flag) {
    goto act_ii_scene_v;
  }
  
  exit_scene(41, romeo);
  
  enter_scene(43, hamlet);
  
  activate_character(48, juliet);
  assign(46, second_person, int_sqrt(46, romeo->value));
  
  activate_character(51, hamlet);
  assign(49, second_person, 2*1);
  
  act_ii_scene_ii:                        /* Questions and the consequences thereof */
  
  activate_character(56, juliet);
  comp1 = value_of(54, first_person);
  comp2 = value_of(54, second_person);
  truth_flag = (comp1 > comp2);
  
  activate_character(59, hamlet);
  if (truth_flag) {
    goto act_ii_scene_iii;
  }
  
  activate_character(63, juliet);
  comp1 = int_mod(60, romeo->value, value_of(60, first_person));
  comp2 = 0;
  truth_flag = (comp1 == comp2);
  
  activate_character(67, hamlet);
  if (truth_flag) {
    goto act_ii_scene_iv;
  }
  assign(65, second_person, int_add(65, value_of(65, second_person), 1));
  
  activate_character(70, juliet);
  goto act_ii_scene_ii;
  
  act_ii_scene_iii:                       /* Romeo must die */
  
  exit_scene(72, hamlet);
  
  enter_scene(74, romeo);
  
  activate_character(79, juliet);
  int_output(77, second_person);
  
  exit_scene(79, juliet);
  
  enter_scene(81, hamlet);
  
  activate_character(88, romeo);
  assign(85, second_person, int_sub(84, 0, int_add(84, 2*2*2*(-1), 2*(-1))));
  char_output(86, second_person);
  
  exit_scene(88, romeo);
  
  enter_scene(90, juliet);
  
  act_ii_scene_iv:                        /* One small dog at a time */
  
  exit_scene(94, hamlet);
  
  enter_scene(96, romeo);
  
  activate_character(102, juliet);
  assign(99, second_person, int_add(99, value_of(99, second_person), 1));
  goto act_ii_scene_i;
  
  act_ii_scene_v:                         /* Fin */
  
  exit_scene_all(104);
  
  return 0;
}
